### ISSUE TITLE
Crash when launching

### ISSUE THREAD

**Issue by Jan200101** [SapuSeven/BetterUntis#8]
Tested with the 3.0.0-DEBUG+11.60 apk

```
10-09 15:18:14.116  6140  6140 E BetterUntis: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sapuseven.untis.debug/com.sapuseven.untis.activities.MainActivity}: java.lang.IllegalArgumentException: No enum constant com.sapuseven.untis.helpers.timetable.TimetableDatabaseInterface.Type.com.sapuseven.untis.activities.MainActivity@d0001d8
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at android.app.ActivityThread.performLaunchActivity(Unknown Source:591)
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:36)
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:57)
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:99)
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:34)
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at android.app.ActivityThread$H.handleMessage(Unknown Source:36)
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at android.os.Handler.dispatchMessage(Unknown Source:21)
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at android.os.Looper.loop(Unknown Source:208)
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at android.app.ActivityThread.main(Unknown Source:107)
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at java.lang.reflect.Method.invoke(Native Method)
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:274)
10-09 15:18:14.116  6140  6140 E BetterUntis: Caused by: java.lang.IllegalArgumentException: No enum constant com.sapuseven.untis.helpers.timetable.TimetableDatabaseInterface.Type.com.sapuseven.untis.activities.MainActivity@d0001d8
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at java.lang.Enum.valueOf(Enum.java:258)
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at com.sapuseven.untis.helpers.timetable.TimetableDatabaseInterface$Type.valueOf(Unknown Source:2)
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at com.sapuseven.untis.activities.MainActivity.showPersonalTimetable(MainActivity.kt:158)
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at com.sapuseven.untis.activities.MainActivity.onCreate(MainActivity.kt:126)
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at android.app.Activity.performCreate(Unknown Source:16)
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at android.app.Activity.performCreate(Unknown Source:1)
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3)
10-09 15:18:14.116  6140  6140 E BetterUntis: 	at android.app.ActivityThread.performLaunchActivity(Unknown Source:368)
10-09 15:18:14.116  6140  6140 E BetterUntis: 	... 11 more
10-09 15:18:30.980  6181  6181 E BetterUntis: Application crashed!
```

**Comment by SapuSeven** [comment]
Thanks, should be fixed in the new build.

The problem was that the IDE marked some qualifier names as redundant when they were actually required.

**Comment by Jan200101** [comment]
Issue fixed

**Comment by Jan200101** [comment]
Found another
```
10-10 11:24:42.125 10061 10061 E BetterUntis: Application crashed!
10-10 11:24:42.125 10061 10061 E BetterUntis: java.lang.ClassCastException: kotlinx.serialization.cbor.Cbor$CborReader cannot be cast to kotlinx.serialization.json.JsonInput
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at com.sapuseven.untis.models.UnknownObject$Companion.deserialize(UnknownObject.kt:20)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at com.sapuseven.untis.models.UnknownObject$Companion.deserialize(UnknownObject.kt:11)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Coders.kt:113)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.ElementValueDecoder.decodeSerializableValue(ElementWise.kt:91)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.Decoder$DefaultImpls.decodeNullableSerializableValue(Coders.kt:116)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.ElementValueDecoder.decodeNullableSerializableValue(ElementWise.kt:91)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.ElementValueDecoder.decodeNullableSerializableElement(ElementWise.kt:144)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at com.sapuseven.untis.models.untis.timetable.Period$$serializer.deserialize(Unknown Source:467)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at com.sapuseven.untis.models.untis.timetable.Period$$serializer.deserialize(Period.kt:7)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Coders.kt:113)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.ElementValueDecoder.decodeSerializableValue(ElementWise.kt:91)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:142)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.internal.ListLikeSerializer.readItem(CollectionSerializers.kt:98)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.readItem$default(CollectionSerializers.kt:70)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:51)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:61)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Coders.kt:113)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.ElementValueDecoder.decodeSerializableValue(ElementWise.kt:91)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:142)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at com.sapuseven.untis.helpers.timetable.TimetableCache$CacheObject$$serializer.deserialize(Unknown Source:75)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at com.sapuseven.untis.helpers.timetable.TimetableCache$CacheObject$$serializer.deserialize(TimetableCache.kt:41)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Coders.kt:113)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.ElementValueDecoder.decodeSerializableValue(ElementWise.kt:91)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.CoreKt.decode(Core.kt:79)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.cbor.Cbor.load(Cbor.kt:397)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.serialization.cbor.Cbor$Companion.load(Cbor.kt:382)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at com.sapuseven.untis.helpers.timetable.TimetableCache.load(TimetableCache.kt:24)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at com.sapuseven.untis.helpers.timetable.TimetableLoader.loadFromCache(TimetableLoader.kt:62)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at com.sapuseven.untis.helpers.timetable.TimetableLoader.access$loadFromCache(TimetableLoader.kt:28)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at com.sapuseven.untis.helpers.timetable.TimetableLoader$load$1.invokeSuspend(TimetableLoader.kt:51)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at android.os.Handler.handleCallback(Unknown Source:2)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at android.os.Handler.dispatchMessage(Unknown Source:4)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at android.os.Looper.loop(Unknown Source:208)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at android.app.ActivityThread.main(Unknown Source:107)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at java.lang.reflect.Method.invoke(Native Method)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
10-10 11:24:42.125 10061 10061 E BetterUntis: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:274)
```

**Comment by SapuSeven** [comment]
I should really test my changes better... Should be fixed in [build#64](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=64)

**Comment by Jan200101** [comment]
it seemingly has no end
```
10-10 14:11:22.470 19450 19450 E BetterUntis: Application crashed!
10-10 14:11:22.470 19450 19450 E BetterUntis: kotlinx.serialization.SerializationException: com.sapuseven.untis.models.untis.timetable.Period does not contain element with name ''
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at kotlinx.serialization.ShorthandsKt.getElementIndexOrThrow(Shorthands.kt:58)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at kotlinx.serialization.cbor.Cbor$CborReader.decodeElementIndex(Cbor.kt:227)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at com.sapuseven.untis.models.untis.timetable.Period$$serializer.deserialize(Unknown Source:38)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at com.sapuseven.untis.models.untis.timetable.Period$$serializer.deserialize(Period.kt:7)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Coders.kt:113)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at kotlinx.serialization.ElementValueDecoder.decodeSerializableValue(ElementWise.kt:91)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:142)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at kotlinx.serialization.internal.ListLikeSerializer.readItem(CollectionSerializers.kt:98)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.readItem$default(CollectionSerializers.kt:70)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:51)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:61)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Coders.kt:113)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at kotlinx.serialization.ElementValueDecoder.decodeSerializableValue(ElementWise.kt:91)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:142)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at com.sapuseven.untis.helpers.timetable.TimetableCache$CacheObject$$serializer.deserialize(Unknown Source:75)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at com.sapuseven.untis.helpers.timetable.TimetableCache$CacheObject$$serializer.deserialize(TimetableCache.kt:41)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Coders.kt:113)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at kotlinx.serialization.ElementValueDecoder.decodeSerializableValue(ElementWise.kt:91)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at kotlinx.serialization.CoreKt.decode(Core.kt:79)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at kotlinx.serialization.cbor.Cbor.load(Cbor.kt:397)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at kotlinx.serialization.cbor.Cbor$Companion.load(Cbor.kt:382)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at com.sapuseven.untis.helpers.timetable.TimetableCache.load(TimetableCache.kt:24)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at com.sapuseven.untis.helpers.timetable.TimetableLoader.loadFromCache(TimetableLoader.kt:62)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at com.sapuseven.untis.helpers.timetable.TimetableLoader.access$loadFromCache(TimetableLoader.kt:28)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at com.sapuseven.untis.helpers.timetable.TimetableLoader$load$1.invokeSuspend(TimetableLoader.kt:51)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at android.os.Handler.handleCallback(Unknown Source:2)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at android.os.Handler.dispatchMessage(Unknown Source:4)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at android.os.Looper.loop(Unknown Source:208)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at android.app.ActivityThread.main(Unknown Source:107)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at java.lang.reflect.Method.invoke(Native Method)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
10-10 14:11:22.470 19450 19450 E BetterUntis: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:274)
```

**Comment by SapuSeven** [comment]
Can you try deleting the app cache?

**Comment by Jan200101** [comment]
clearing the cache alone won't cause a crash on the first run but the error is still shown
any following run of the app will cause the same behavior as before

**Comment by SapuSeven** [comment]
Please try again with the latest [build#69](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=69). I'm really sorry for bothering but I can't really test it myself as the problem is specific to your school.
Don't forget to clean the cache first.

**Comment by SapuSeven** [comment]
Please try again with the latest [build#71](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=71). I'm really sorry for bothering but I can't really test it myself as the problem is specific to your school.
Don't forget to clean the cache first.

**Comment by Jan200101** [comment]
fixed
